// Generated by gencpp from file movement/display_set_font.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_DISPLAY_SET_FONT_H
#define MOVEMENT_MESSAGE_DISPLAY_SET_FONT_H

#include <ros/service_traits.h>


#include <movement/display_set_fontRequest.h>
#include <movement/display_set_fontResponse.h>


namespace movement
{

struct display_set_font
{

typedef display_set_fontRequest Request;
typedef display_set_fontResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_set_font
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::display_set_font > {
  static const char* value()
  {
    return "78ff6c1f16d92deedcc7d16bd2cddfbf";
  }

  static const char* value(const ::movement::display_set_font&) { return value(); }
};

template<>
struct DataType< ::movement::display_set_font > {
  static const char* value()
  {
    return "movement/display_set_font";
  }

  static const char* value(const ::movement::display_set_font&) { return value(); }
};


// service_traits::MD5Sum< ::movement::display_set_fontRequest> should match
// service_traits::MD5Sum< ::movement::display_set_font >
template<>
struct MD5Sum< ::movement::display_set_fontRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::display_set_font >::value();
  }
  static const char* value(const ::movement::display_set_fontRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::display_set_fontRequest> should match
// service_traits::DataType< ::movement::display_set_font >
template<>
struct DataType< ::movement::display_set_fontRequest>
{
  static const char* value()
  {
    return DataType< ::movement::display_set_font >::value();
  }
  static const char* value(const ::movement::display_set_fontRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::display_set_fontResponse> should match
// service_traits::MD5Sum< ::movement::display_set_font >
template<>
struct MD5Sum< ::movement::display_set_fontResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::display_set_font >::value();
  }
  static const char* value(const ::movement::display_set_fontResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::display_set_fontResponse> should match
// service_traits::DataType< ::movement::display_set_font >
template<>
struct DataType< ::movement::display_set_fontResponse>
{
  static const char* value()
  {
    return DataType< ::movement::display_set_font >::value();
  }
  static const char* value(const ::movement::display_set_fontResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_DISPLAY_SET_FONT_H
