// Generated by gencpp from file movement/display_draw_pixel.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXEL_H
#define MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXEL_H

#include <ros/service_traits.h>


#include <movement/display_draw_pixelRequest.h>
#include <movement/display_draw_pixelResponse.h>


namespace movement
{

struct display_draw_pixel
{

typedef display_draw_pixelRequest Request;
typedef display_draw_pixelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_pixel
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::display_draw_pixel > {
  static const char* value()
  {
    return "e8e87fb7b87ab83a24bea771b7fc11df";
  }

  static const char* value(const ::movement::display_draw_pixel&) { return value(); }
};

template<>
struct DataType< ::movement::display_draw_pixel > {
  static const char* value()
  {
    return "movement/display_draw_pixel";
  }

  static const char* value(const ::movement::display_draw_pixel&) { return value(); }
};


// service_traits::MD5Sum< ::movement::display_draw_pixelRequest> should match
// service_traits::MD5Sum< ::movement::display_draw_pixel >
template<>
struct MD5Sum< ::movement::display_draw_pixelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::display_draw_pixel >::value();
  }
  static const char* value(const ::movement::display_draw_pixelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::display_draw_pixelRequest> should match
// service_traits::DataType< ::movement::display_draw_pixel >
template<>
struct DataType< ::movement::display_draw_pixelRequest>
{
  static const char* value()
  {
    return DataType< ::movement::display_draw_pixel >::value();
  }
  static const char* value(const ::movement::display_draw_pixelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::display_draw_pixelResponse> should match
// service_traits::MD5Sum< ::movement::display_draw_pixel >
template<>
struct MD5Sum< ::movement::display_draw_pixelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::display_draw_pixel >::value();
  }
  static const char* value(const ::movement::display_draw_pixelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::display_draw_pixelResponse> should match
// service_traits::DataType< ::movement::display_draw_pixel >
template<>
struct DataType< ::movement::display_draw_pixelResponse>
{
  static const char* value()
  {
    return DataType< ::movement::display_draw_pixel >::value();
  }
  static const char* value(const ::movement::display_draw_pixelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXEL_H
