// Generated by gencpp from file movement/display_draw_pixelRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXELREQUEST_H
#define MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct display_draw_pixelRequest_
{
  typedef display_draw_pixelRequest_<ContainerAllocator> Type;

  display_draw_pixelRequest_()
    : x1(0)
    , y1(0)  {
    }
  display_draw_pixelRequest_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)  {
  (void)_alloc;
    }



   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _y1_type;
  _y1_type y1;





  typedef boost::shared_ptr< ::movement::display_draw_pixelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::display_draw_pixelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct display_draw_pixelRequest_

typedef ::movement::display_draw_pixelRequest_<std::allocator<void> > display_draw_pixelRequest;

typedef boost::shared_ptr< ::movement::display_draw_pixelRequest > display_draw_pixelRequestPtr;
typedef boost::shared_ptr< ::movement::display_draw_pixelRequest const> display_draw_pixelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::display_draw_pixelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::display_draw_pixelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::display_draw_pixelRequest_<ContainerAllocator1> & lhs, const ::movement::display_draw_pixelRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::display_draw_pixelRequest_<ContainerAllocator1> & lhs, const ::movement::display_draw_pixelRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::display_draw_pixelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::display_draw_pixelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::display_draw_pixelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a417c344be1a26b28c26afdee67552f";
  }

  static const char* value(const ::movement::display_draw_pixelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a417c344be1a26bULL;
  static const uint64_t static_value2 = 0x28c26afdee67552fULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/display_draw_pixelRequest";
  }

  static const char* value(const ::movement::display_draw_pixelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x1\n"
"int32 y1\n"
;
  }

  static const char* value(const ::movement::display_draw_pixelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct display_draw_pixelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::display_draw_pixelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::display_draw_pixelRequest_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_DISPLAY_DRAW_PIXELREQUEST_H
