// Generated by gencpp from file movement/field_set_floatRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_FIELD_SET_FLOATREQUEST_H
#define MOVEMENT_MESSAGE_FIELD_SET_FLOATREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct field_set_floatRequest_
{
  typedef field_set_floatRequest_<ContainerAllocator> Type;

  field_set_floatRequest_()
    : field(0)
    , index(0)
    , value(0.0)  {
    }
  field_set_floatRequest_(const ContainerAllocator& _alloc)
    : field(0)
    , index(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _field_type;
  _field_type field;

   typedef int32_t _index_type;
  _index_type index;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::movement::field_set_floatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::field_set_floatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct field_set_floatRequest_

typedef ::movement::field_set_floatRequest_<std::allocator<void> > field_set_floatRequest;

typedef boost::shared_ptr< ::movement::field_set_floatRequest > field_set_floatRequestPtr;
typedef boost::shared_ptr< ::movement::field_set_floatRequest const> field_set_floatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::field_set_floatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::field_set_floatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::field_set_floatRequest_<ContainerAllocator1> & lhs, const ::movement::field_set_floatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.field == rhs.field &&
    lhs.index == rhs.index &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::field_set_floatRequest_<ContainerAllocator1> & lhs, const ::movement::field_set_floatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::field_set_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::field_set_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::field_set_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::field_set_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::field_set_floatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::field_set_floatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::field_set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bd2d2b340e1cba56d82c440d4c7c9ce";
  }

  static const char* value(const ::movement::field_set_floatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bd2d2b340e1cba5ULL;
  static const uint64_t static_value2 = 0x6d82c440d4c7c9ceULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::field_set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/field_set_floatRequest";
  }

  static const char* value(const ::movement::field_set_floatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::field_set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 field\n"
"int32 index\n"
"float64 value\n"
;
  }

  static const char* value(const ::movement::field_set_floatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::field_set_floatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.field);
      stream.next(m.index);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct field_set_floatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::field_set_floatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::field_set_floatRequest_<ContainerAllocator>& v)
  {
    s << indent << "field: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.field);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_FIELD_SET_FLOATREQUEST_H
