// Generated by gencpp from file movement/get_floatResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_GET_FLOATRESPONSE_H
#define MOVEMENT_MESSAGE_GET_FLOATRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct get_floatResponse_
{
  typedef get_floatResponse_<ContainerAllocator> Type;

  get_floatResponse_()
    : value(0.0)  {
    }
  get_floatResponse_(const ContainerAllocator& _alloc)
    : value(0.0)  {
  (void)_alloc;
    }



   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::movement::get_floatResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::get_floatResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_floatResponse_

typedef ::movement::get_floatResponse_<std::allocator<void> > get_floatResponse;

typedef boost::shared_ptr< ::movement::get_floatResponse > get_floatResponsePtr;
typedef boost::shared_ptr< ::movement::get_floatResponse const> get_floatResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::get_floatResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::get_floatResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::get_floatResponse_<ContainerAllocator1> & lhs, const ::movement::get_floatResponse_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::get_floatResponse_<ContainerAllocator1> & lhs, const ::movement::get_floatResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::get_floatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::get_floatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::get_floatResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::get_floatResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::get_floatResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::get_floatResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::get_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b1594d2b74931ef8fe7be8e2d594455";
  }

  static const char* value(const ::movement::get_floatResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b1594d2b74931efULL;
  static const uint64_t static_value2 = 0x8fe7be8e2d594455ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::get_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/get_floatResponse";
  }

  static const char* value(const ::movement::get_floatResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::get_floatResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 value\n"
"\n"
;
  }

  static const char* value(const ::movement::get_floatResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::get_floatResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_floatResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::get_floatResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::get_floatResponse_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_GET_FLOATRESPONSE_H
