// Generated by gencpp from file movement/motor_set_control_pidRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H
#define MOVEMENT_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct motor_set_control_pidRequest_
{
  typedef motor_set_control_pidRequest_<ContainerAllocator> Type;

  motor_set_control_pidRequest_()
    : controlp(0.0)
    , controli(0.0)
    , controld(0.0)  {
    }
  motor_set_control_pidRequest_(const ContainerAllocator& _alloc)
    : controlp(0.0)
    , controli(0.0)
    , controld(0.0)  {
  (void)_alloc;
    }



   typedef double _controlp_type;
  _controlp_type controlp;

   typedef double _controli_type;
  _controli_type controli;

   typedef double _controld_type;
  _controld_type controld;





  typedef boost::shared_ptr< ::movement::motor_set_control_pidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::motor_set_control_pidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_set_control_pidRequest_

typedef ::movement::motor_set_control_pidRequest_<std::allocator<void> > motor_set_control_pidRequest;

typedef boost::shared_ptr< ::movement::motor_set_control_pidRequest > motor_set_control_pidRequestPtr;
typedef boost::shared_ptr< ::movement::motor_set_control_pidRequest const> motor_set_control_pidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::motor_set_control_pidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::motor_set_control_pidRequest_<ContainerAllocator1> & lhs, const ::movement::motor_set_control_pidRequest_<ContainerAllocator2> & rhs)
{
  return lhs.controlp == rhs.controlp &&
    lhs.controli == rhs.controli &&
    lhs.controld == rhs.controld;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::motor_set_control_pidRequest_<ContainerAllocator1> & lhs, const ::movement::motor_set_control_pidRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::motor_set_control_pidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::motor_set_control_pidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::motor_set_control_pidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ebf8f7154a3c8eec118cec294f2c32c";
  }

  static const char* value(const ::movement::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ebf8f7154a3c8eeULL;
  static const uint64_t static_value2 = 0xc118cec294f2c32cULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/motor_set_control_pidRequest";
  }

  static const char* value(const ::movement::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 controlp\n"
"float64 controli\n"
"float64 controld\n"
;
  }

  static const char* value(const ::movement::motor_set_control_pidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controlp);
      stream.next(m.controli);
      stream.next(m.controld);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_set_control_pidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::motor_set_control_pidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::motor_set_control_pidRequest_<ContainerAllocator>& v)
  {
    s << indent << "controlp: ";
    Printer<double>::stream(s, indent + "  ", v.controlp);
    s << indent << "controli: ";
    Printer<double>::stream(s, indent + "  ", v.controli);
    s << indent << "controld: ";
    Printer<double>::stream(s, indent + "  ", v.controld);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_MOTOR_SET_CONTROL_PIDREQUEST_H
