// Generated by gencpp from file movement/node_set_joint_position.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_SET_JOINT_POSITION_H
#define MOVEMENT_MESSAGE_NODE_SET_JOINT_POSITION_H

#include <ros/service_traits.h>


#include <movement/node_set_joint_positionRequest.h>
#include <movement/node_set_joint_positionResponse.h>


namespace movement
{

struct node_set_joint_position
{

typedef node_set_joint_positionRequest Request;
typedef node_set_joint_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_set_joint_position
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_set_joint_position > {
  static const char* value()
  {
    return "5c6d60bc617f1348200743f9a8544085";
  }

  static const char* value(const ::movement::node_set_joint_position&) { return value(); }
};

template<>
struct DataType< ::movement::node_set_joint_position > {
  static const char* value()
  {
    return "movement/node_set_joint_position";
  }

  static const char* value(const ::movement::node_set_joint_position&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_set_joint_positionRequest> should match
// service_traits::MD5Sum< ::movement::node_set_joint_position >
template<>
struct MD5Sum< ::movement::node_set_joint_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_set_joint_position >::value();
  }
  static const char* value(const ::movement::node_set_joint_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_set_joint_positionRequest> should match
// service_traits::DataType< ::movement::node_set_joint_position >
template<>
struct DataType< ::movement::node_set_joint_positionRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_set_joint_position >::value();
  }
  static const char* value(const ::movement::node_set_joint_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_set_joint_positionResponse> should match
// service_traits::MD5Sum< ::movement::node_set_joint_position >
template<>
struct MD5Sum< ::movement::node_set_joint_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_set_joint_position >::value();
  }
  static const char* value(const ::movement::node_set_joint_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_set_joint_positionResponse> should match
// service_traits::DataType< ::movement::node_set_joint_position >
template<>
struct DataType< ::movement::node_set_joint_positionResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_set_joint_position >::value();
  }
  static const char* value(const ::movement::node_set_joint_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_SET_JOINT_POSITION_H
