// Generated by gencpp from file movement/node_get_id.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_GET_ID_H
#define MOVEMENT_MESSAGE_NODE_GET_ID_H

#include <ros/service_traits.h>


#include <movement/node_get_idRequest.h>
#include <movement/node_get_idResponse.h>


namespace movement
{

struct node_get_id
{

typedef node_get_idRequest Request;
typedef node_get_idResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_id
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_get_id > {
  static const char* value()
  {
    return "16a06b427b76c7c64b73962f4f092416";
  }

  static const char* value(const ::movement::node_get_id&) { return value(); }
};

template<>
struct DataType< ::movement::node_get_id > {
  static const char* value()
  {
    return "movement/node_get_id";
  }

  static const char* value(const ::movement::node_get_id&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_get_idRequest> should match
// service_traits::MD5Sum< ::movement::node_get_id >
template<>
struct MD5Sum< ::movement::node_get_idRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_id >::value();
  }
  static const char* value(const ::movement::node_get_idRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_idRequest> should match
// service_traits::DataType< ::movement::node_get_id >
template<>
struct DataType< ::movement::node_get_idRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_id >::value();
  }
  static const char* value(const ::movement::node_get_idRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_get_idResponse> should match
// service_traits::MD5Sum< ::movement::node_get_id >
template<>
struct MD5Sum< ::movement::node_get_idResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_id >::value();
  }
  static const char* value(const ::movement::node_get_idResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_idResponse> should match
// service_traits::DataType< ::movement::node_get_id >
template<>
struct DataType< ::movement::node_get_idResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_id >::value();
  }
  static const char* value(const ::movement::node_get_idResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_GET_ID_H
