// Generated by gencpp from file movement/node_set_velocity.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_SET_VELOCITY_H
#define MOVEMENT_MESSAGE_NODE_SET_VELOCITY_H

#include <ros/service_traits.h>


#include <movement/node_set_velocityRequest.h>
#include <movement/node_set_velocityResponse.h>


namespace movement
{

struct node_set_velocity
{

typedef node_set_velocityRequest Request;
typedef node_set_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_set_velocity
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_set_velocity > {
  static const char* value()
  {
    return "bbe5d1dd420b6f268ed5aee8db339832";
  }

  static const char* value(const ::movement::node_set_velocity&) { return value(); }
};

template<>
struct DataType< ::movement::node_set_velocity > {
  static const char* value()
  {
    return "movement/node_set_velocity";
  }

  static const char* value(const ::movement::node_set_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_set_velocityRequest> should match
// service_traits::MD5Sum< ::movement::node_set_velocity >
template<>
struct MD5Sum< ::movement::node_set_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_set_velocity >::value();
  }
  static const char* value(const ::movement::node_set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_set_velocityRequest> should match
// service_traits::DataType< ::movement::node_set_velocity >
template<>
struct DataType< ::movement::node_set_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_set_velocity >::value();
  }
  static const char* value(const ::movement::node_set_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_set_velocityResponse> should match
// service_traits::MD5Sum< ::movement::node_set_velocity >
template<>
struct MD5Sum< ::movement::node_set_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_set_velocity >::value();
  }
  static const char* value(const ::movement::node_set_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_set_velocityResponse> should match
// service_traits::DataType< ::movement::node_set_velocity >
template<>
struct DataType< ::movement::node_set_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_set_velocity >::value();
  }
  static const char* value(const ::movement::node_set_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_SET_VELOCITY_H
