// Generated by gencpp from file movement/node_get_status.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_GET_STATUS_H
#define MOVEMENT_MESSAGE_NODE_GET_STATUS_H

#include <ros/service_traits.h>


#include <movement/node_get_statusRequest.h>
#include <movement/node_get_statusResponse.h>


namespace movement
{

struct node_get_status
{

typedef node_get_statusRequest Request;
typedef node_get_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_status
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_get_status > {
  static const char* value()
  {
    return "9d10c008835cf4bd024a6af9eca46c13";
  }

  static const char* value(const ::movement::node_get_status&) { return value(); }
};

template<>
struct DataType< ::movement::node_get_status > {
  static const char* value()
  {
    return "movement/node_get_status";
  }

  static const char* value(const ::movement::node_get_status&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_get_statusRequest> should match
// service_traits::MD5Sum< ::movement::node_get_status >
template<>
struct MD5Sum< ::movement::node_get_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_status >::value();
  }
  static const char* value(const ::movement::node_get_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_statusRequest> should match
// service_traits::DataType< ::movement::node_get_status >
template<>
struct DataType< ::movement::node_get_statusRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_status >::value();
  }
  static const char* value(const ::movement::node_get_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_get_statusResponse> should match
// service_traits::MD5Sum< ::movement::node_get_status >
template<>
struct MD5Sum< ::movement::node_get_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_status >::value();
  }
  static const char* value(const ::movement::node_get_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_statusResponse> should match
// service_traits::DataType< ::movement::node_get_status >
template<>
struct DataType< ::movement::node_get_statusResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_status >::value();
  }
  static const char* value(const ::movement::node_get_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_GET_STATUS_H
