// Generated by gencpp from file movement/node_get_contact_points.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_GET_CONTACT_POINTS_H
#define MOVEMENT_MESSAGE_NODE_GET_CONTACT_POINTS_H

#include <ros/service_traits.h>


#include <movement/node_get_contact_pointsRequest.h>
#include <movement/node_get_contact_pointsResponse.h>


namespace movement
{

struct node_get_contact_points
{

typedef node_get_contact_pointsRequest Request;
typedef node_get_contact_pointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_contact_points
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_get_contact_points > {
  static const char* value()
  {
    return "2b8ca1a0f35ff5c1915577923081855f";
  }

  static const char* value(const ::movement::node_get_contact_points&) { return value(); }
};

template<>
struct DataType< ::movement::node_get_contact_points > {
  static const char* value()
  {
    return "movement/node_get_contact_points";
  }

  static const char* value(const ::movement::node_get_contact_points&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_get_contact_pointsRequest> should match
// service_traits::MD5Sum< ::movement::node_get_contact_points >
template<>
struct MD5Sum< ::movement::node_get_contact_pointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_contact_points >::value();
  }
  static const char* value(const ::movement::node_get_contact_pointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_contact_pointsRequest> should match
// service_traits::DataType< ::movement::node_get_contact_points >
template<>
struct DataType< ::movement::node_get_contact_pointsRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_contact_points >::value();
  }
  static const char* value(const ::movement::node_get_contact_pointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_get_contact_pointsResponse> should match
// service_traits::MD5Sum< ::movement::node_get_contact_points >
template<>
struct MD5Sum< ::movement::node_get_contact_pointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_contact_points >::value();
  }
  static const char* value(const ::movement::node_get_contact_pointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_contact_pointsResponse> should match
// service_traits::DataType< ::movement::node_get_contact_points >
template<>
struct DataType< ::movement::node_get_contact_pointsResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_contact_points >::value();
  }
  static const char* value(const ::movement::node_get_contact_pointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_GET_CONTACT_POINTS_H
