// Generated by gencpp from file movement/node_set_stringRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_SET_STRINGREQUEST_H
#define MOVEMENT_MESSAGE_NODE_SET_STRINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct node_set_stringRequest_
{
  typedef node_set_stringRequest_<ContainerAllocator> Type;

  node_set_stringRequest_()
    : node(0)
    , state_name()  {
    }
  node_set_stringRequest_(const ContainerAllocator& _alloc)
    : node(0)
    , state_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _node_type;
  _node_type node;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_name_type;
  _state_name_type state_name;





  typedef boost::shared_ptr< ::movement::node_set_stringRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::node_set_stringRequest_<ContainerAllocator> const> ConstPtr;

}; // struct node_set_stringRequest_

typedef ::movement::node_set_stringRequest_<std::allocator<void> > node_set_stringRequest;

typedef boost::shared_ptr< ::movement::node_set_stringRequest > node_set_stringRequestPtr;
typedef boost::shared_ptr< ::movement::node_set_stringRequest const> node_set_stringRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::node_set_stringRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::node_set_stringRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::node_set_stringRequest_<ContainerAllocator1> & lhs, const ::movement::node_set_stringRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node &&
    lhs.state_name == rhs.state_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::node_set_stringRequest_<ContainerAllocator1> & lhs, const ::movement::node_set_stringRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::node_set_stringRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::node_set_stringRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::node_set_stringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::node_set_stringRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::node_set_stringRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::node_set_stringRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::node_set_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5262a198fe3532bd7eee27115a5826d0";
  }

  static const char* value(const ::movement::node_set_stringRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5262a198fe3532bdULL;
  static const uint64_t static_value2 = 0x7eee27115a5826d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::node_set_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/node_set_stringRequest";
  }

  static const char* value(const ::movement::node_set_stringRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::node_set_stringRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 node\n"
"string state_name\n"
;
  }

  static const char* value(const ::movement::node_set_stringRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::node_set_stringRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.state_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_set_stringRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::node_set_stringRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::node_set_stringRequest_<ContainerAllocator>& v)
  {
    s << indent << "node: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.node);
    s << indent << "state_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_SET_STRINGREQUEST_H
