// Generated by gencpp from file movement/node_get_center_of_mass.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_NODE_GET_CENTER_OF_MASS_H
#define MOVEMENT_MESSAGE_NODE_GET_CENTER_OF_MASS_H

#include <ros/service_traits.h>


#include <movement/node_get_center_of_massRequest.h>
#include <movement/node_get_center_of_massResponse.h>


namespace movement
{

struct node_get_center_of_mass
{

typedef node_get_center_of_massRequest Request;
typedef node_get_center_of_massResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_center_of_mass
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::node_get_center_of_mass > {
  static const char* value()
  {
    return "08baa9a118e7086ad4f02f73fae3dd80";
  }

  static const char* value(const ::movement::node_get_center_of_mass&) { return value(); }
};

template<>
struct DataType< ::movement::node_get_center_of_mass > {
  static const char* value()
  {
    return "movement/node_get_center_of_mass";
  }

  static const char* value(const ::movement::node_get_center_of_mass&) { return value(); }
};


// service_traits::MD5Sum< ::movement::node_get_center_of_massRequest> should match
// service_traits::MD5Sum< ::movement::node_get_center_of_mass >
template<>
struct MD5Sum< ::movement::node_get_center_of_massRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_center_of_mass >::value();
  }
  static const char* value(const ::movement::node_get_center_of_massRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_center_of_massRequest> should match
// service_traits::DataType< ::movement::node_get_center_of_mass >
template<>
struct DataType< ::movement::node_get_center_of_massRequest>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_center_of_mass >::value();
  }
  static const char* value(const ::movement::node_get_center_of_massRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::node_get_center_of_massResponse> should match
// service_traits::MD5Sum< ::movement::node_get_center_of_mass >
template<>
struct MD5Sum< ::movement::node_get_center_of_massResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::node_get_center_of_mass >::value();
  }
  static const char* value(const ::movement::node_get_center_of_massResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::node_get_center_of_massResponse> should match
// service_traits::DataType< ::movement::node_get_center_of_mass >
template<>
struct DataType< ::movement::node_get_center_of_massResponse>
{
  static const char* value()
  {
    return DataType< ::movement::node_get_center_of_mass >::value();
  }
  static const char* value(const ::movement::node_get_center_of_massResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_NODE_GET_CENTER_OF_MASS_H
