// Generated by gencpp from file movement/range_finder_get_info.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_RANGE_FINDER_GET_INFO_H
#define MOVEMENT_MESSAGE_RANGE_FINDER_GET_INFO_H

#include <ros/service_traits.h>


#include <movement/range_finder_get_infoRequest.h>
#include <movement/range_finder_get_infoResponse.h>


namespace movement
{

struct range_finder_get_info
{

typedef range_finder_get_infoRequest Request;
typedef range_finder_get_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct range_finder_get_info
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::range_finder_get_info > {
  static const char* value()
  {
    return "7de8466f9b36888a8538ac7cacbb5d90";
  }

  static const char* value(const ::movement::range_finder_get_info&) { return value(); }
};

template<>
struct DataType< ::movement::range_finder_get_info > {
  static const char* value()
  {
    return "movement/range_finder_get_info";
  }

  static const char* value(const ::movement::range_finder_get_info&) { return value(); }
};


// service_traits::MD5Sum< ::movement::range_finder_get_infoRequest> should match
// service_traits::MD5Sum< ::movement::range_finder_get_info >
template<>
struct MD5Sum< ::movement::range_finder_get_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::range_finder_get_info >::value();
  }
  static const char* value(const ::movement::range_finder_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::range_finder_get_infoRequest> should match
// service_traits::DataType< ::movement::range_finder_get_info >
template<>
struct DataType< ::movement::range_finder_get_infoRequest>
{
  static const char* value()
  {
    return DataType< ::movement::range_finder_get_info >::value();
  }
  static const char* value(const ::movement::range_finder_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::range_finder_get_infoResponse> should match
// service_traits::MD5Sum< ::movement::range_finder_get_info >
template<>
struct MD5Sum< ::movement::range_finder_get_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::range_finder_get_info >::value();
  }
  static const char* value(const ::movement::range_finder_get_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::range_finder_get_infoResponse> should match
// service_traits::DataType< ::movement::range_finder_get_info >
template<>
struct DataType< ::movement::range_finder_get_infoResponse>
{
  static const char* value()
  {
    return DataType< ::movement::range_finder_get_info >::value();
  }
  static const char* value(const ::movement::range_finder_get_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_RANGE_FINDER_GET_INFO_H
