// Generated by gencpp from file movement/robot_set_modeResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_ROBOT_SET_MODERESPONSE_H
#define MOVEMENT_MESSAGE_ROBOT_SET_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement
{
template <class ContainerAllocator>
struct robot_set_modeResponse_
{
  typedef robot_set_modeResponse_<ContainerAllocator> Type;

  robot_set_modeResponse_()
    : success(0)  {
    }
  robot_set_modeResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::movement::robot_set_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement::robot_set_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_set_modeResponse_

typedef ::movement::robot_set_modeResponse_<std::allocator<void> > robot_set_modeResponse;

typedef boost::shared_ptr< ::movement::robot_set_modeResponse > robot_set_modeResponsePtr;
typedef boost::shared_ptr< ::movement::robot_set_modeResponse const> robot_set_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement::robot_set_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement::robot_set_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement::robot_set_modeResponse_<ContainerAllocator1> & lhs, const ::movement::robot_set_modeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement::robot_set_modeResponse_<ContainerAllocator1> & lhs, const ::movement::robot_set_modeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement::robot_set_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement::robot_set_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::robot_set_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement::robot_set_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::robot_set_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement::robot_set_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement::robot_set_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b13460cb14006d3852674b4c614f25f";
  }

  static const char* value(const ::movement::robot_set_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b13460cb14006d3ULL;
  static const uint64_t static_value2 = 0x852674b4c614f25fULL;
};

template<class ContainerAllocator>
struct DataType< ::movement::robot_set_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement/robot_set_modeResponse";
  }

  static const char* value(const ::movement::robot_set_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement::robot_set_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 success\n"
"\n"
;
  }

  static const char* value(const ::movement::robot_set_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement::robot_set_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_set_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement::robot_set_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement::robot_set_modeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MESSAGE_ROBOT_SET_MODERESPONSE_H
