// Generated by gencpp from file movement/set_float.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MESSAGE_SET_FLOAT_H
#define MOVEMENT_MESSAGE_SET_FLOAT_H

#include <ros/service_traits.h>


#include <movement/set_floatRequest.h>
#include <movement/set_floatResponse.h>


namespace movement
{

struct set_float
{

typedef set_floatRequest Request;
typedef set_floatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_float
} // namespace movement


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement::set_float > {
  static const char* value()
  {
    return "0f0509b4253b73657cb37e93f4f2960c";
  }

  static const char* value(const ::movement::set_float&) { return value(); }
};

template<>
struct DataType< ::movement::set_float > {
  static const char* value()
  {
    return "movement/set_float";
  }

  static const char* value(const ::movement::set_float&) { return value(); }
};


// service_traits::MD5Sum< ::movement::set_floatRequest> should match
// service_traits::MD5Sum< ::movement::set_float >
template<>
struct MD5Sum< ::movement::set_floatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement::set_float >::value();
  }
  static const char* value(const ::movement::set_floatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::set_floatRequest> should match
// service_traits::DataType< ::movement::set_float >
template<>
struct DataType< ::movement::set_floatRequest>
{
  static const char* value()
  {
    return DataType< ::movement::set_float >::value();
  }
  static const char* value(const ::movement::set_floatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement::set_floatResponse> should match
// service_traits::MD5Sum< ::movement::set_float >
template<>
struct MD5Sum< ::movement::set_floatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement::set_float >::value();
  }
  static const char* value(const ::movement::set_floatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement::set_floatResponse> should match
// service_traits::DataType< ::movement::set_float >
template<>
struct DataType< ::movement::set_floatResponse>
{
  static const char* value()
  {
    return DataType< ::movement::set_float >::value();
  }
  static const char* value(const ::movement::set_floatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MESSAGE_SET_FLOAT_H
