// Generated by gencpp from file tcc_msg/field_disable_sf_tracking.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_FIELD_DISABLE_SF_TRACKING_H
#define TCC_MSG_MESSAGE_FIELD_DISABLE_SF_TRACKING_H

#include <ros/service_traits.h>


#include <tcc_msg/field_disable_sf_trackingRequest.h>
#include <tcc_msg/field_disable_sf_trackingResponse.h>


namespace tcc_msg
{

struct field_disable_sf_tracking
{

typedef field_disable_sf_trackingRequest Request;
typedef field_disable_sf_trackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_disable_sf_tracking
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::field_disable_sf_tracking > {
  static const char* value()
  {
    return "d466ca5c1e4695154072bfb73f0f9e1f";
  }

  static const char* value(const ::tcc_msg::field_disable_sf_tracking&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::field_disable_sf_tracking > {
  static const char* value()
  {
    return "tcc_msg/field_disable_sf_tracking";
  }

  static const char* value(const ::tcc_msg::field_disable_sf_tracking&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::field_disable_sf_trackingRequest> should match
// service_traits::MD5Sum< ::tcc_msg::field_disable_sf_tracking >
template<>
struct MD5Sum< ::tcc_msg::field_disable_sf_trackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::field_disable_sf_tracking >::value();
  }
  static const char* value(const ::tcc_msg::field_disable_sf_trackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::field_disable_sf_trackingRequest> should match
// service_traits::DataType< ::tcc_msg::field_disable_sf_tracking >
template<>
struct DataType< ::tcc_msg::field_disable_sf_trackingRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::field_disable_sf_tracking >::value();
  }
  static const char* value(const ::tcc_msg::field_disable_sf_trackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::field_disable_sf_trackingResponse> should match
// service_traits::MD5Sum< ::tcc_msg::field_disable_sf_tracking >
template<>
struct MD5Sum< ::tcc_msg::field_disable_sf_trackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::field_disable_sf_tracking >::value();
  }
  static const char* value(const ::tcc_msg::field_disable_sf_trackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::field_disable_sf_trackingResponse> should match
// service_traits::DataType< ::tcc_msg::field_disable_sf_tracking >
template<>
struct DataType< ::tcc_msg::field_disable_sf_trackingResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::field_disable_sf_tracking >::value();
  }
  static const char* value(const ::tcc_msg::field_disable_sf_trackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_FIELD_DISABLE_SF_TRACKING_H
