// Generated by gencpp from file tcc_msg/get_float_array.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_GET_FLOAT_ARRAY_H
#define TCC_MSG_MESSAGE_GET_FLOAT_ARRAY_H

#include <ros/service_traits.h>


#include <tcc_msg/get_float_arrayRequest.h>
#include <tcc_msg/get_float_arrayResponse.h>


namespace tcc_msg
{

struct get_float_array
{

typedef get_float_arrayRequest Request;
typedef get_float_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_float_array
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::get_float_array > {
  static const char* value()
  {
    return "7aae320d0f914d7069b041ff192847e1";
  }

  static const char* value(const ::tcc_msg::get_float_array&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::get_float_array > {
  static const char* value()
  {
    return "tcc_msg/get_float_array";
  }

  static const char* value(const ::tcc_msg::get_float_array&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::get_float_arrayRequest> should match
// service_traits::MD5Sum< ::tcc_msg::get_float_array >
template<>
struct MD5Sum< ::tcc_msg::get_float_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_float_array >::value();
  }
  static const char* value(const ::tcc_msg::get_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_float_arrayRequest> should match
// service_traits::DataType< ::tcc_msg::get_float_array >
template<>
struct DataType< ::tcc_msg::get_float_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_float_array >::value();
  }
  static const char* value(const ::tcc_msg::get_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::get_float_arrayResponse> should match
// service_traits::MD5Sum< ::tcc_msg::get_float_array >
template<>
struct MD5Sum< ::tcc_msg::get_float_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_float_array >::value();
  }
  static const char* value(const ::tcc_msg::get_float_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_float_arrayResponse> should match
// service_traits::DataType< ::tcc_msg::get_float_array >
template<>
struct DataType< ::tcc_msg::get_float_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_float_array >::value();
  }
  static const char* value(const ::tcc_msg::get_float_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_GET_FLOAT_ARRAY_H
