// Generated by gencpp from file tcc_msg/get_bool.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_GET_BOOL_H
#define TCC_MSG_MESSAGE_GET_BOOL_H

#include <ros/service_traits.h>


#include <tcc_msg/get_boolRequest.h>
#include <tcc_msg/get_boolResponse.h>


namespace tcc_msg
{

struct get_bool
{

typedef get_boolRequest Request;
typedef get_boolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_bool
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::get_bool > {
  static const char* value()
  {
    return "155bbaa7eff4769d41b3327e2ec91080";
  }

  static const char* value(const ::tcc_msg::get_bool&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::get_bool > {
  static const char* value()
  {
    return "tcc_msg/get_bool";
  }

  static const char* value(const ::tcc_msg::get_bool&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::get_boolRequest> should match
// service_traits::MD5Sum< ::tcc_msg::get_bool >
template<>
struct MD5Sum< ::tcc_msg::get_boolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_bool >::value();
  }
  static const char* value(const ::tcc_msg::get_boolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_boolRequest> should match
// service_traits::DataType< ::tcc_msg::get_bool >
template<>
struct DataType< ::tcc_msg::get_boolRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_bool >::value();
  }
  static const char* value(const ::tcc_msg::get_boolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::get_boolResponse> should match
// service_traits::MD5Sum< ::tcc_msg::get_bool >
template<>
struct MD5Sum< ::tcc_msg::get_boolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_bool >::value();
  }
  static const char* value(const ::tcc_msg::get_boolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_boolResponse> should match
// service_traits::DataType< ::tcc_msg::get_bool >
template<>
struct DataType< ::tcc_msg::get_boolResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_bool >::value();
  }
  static const char* value(const ::tcc_msg::get_boolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_GET_BOOL_H
