// Generated by gencpp from file tcc_msg/get_urdf.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_GET_URDF_H
#define TCC_MSG_MESSAGE_GET_URDF_H

#include <ros/service_traits.h>


#include <tcc_msg/get_urdfRequest.h>
#include <tcc_msg/get_urdfResponse.h>


namespace tcc_msg
{

struct get_urdf
{

typedef get_urdfRequest Request;
typedef get_urdfResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_urdf
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::get_urdf > {
  static const char* value()
  {
    return "9ae31c29f15764629e70e60492948eb1";
  }

  static const char* value(const ::tcc_msg::get_urdf&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::get_urdf > {
  static const char* value()
  {
    return "tcc_msg/get_urdf";
  }

  static const char* value(const ::tcc_msg::get_urdf&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::get_urdfRequest> should match
// service_traits::MD5Sum< ::tcc_msg::get_urdf >
template<>
struct MD5Sum< ::tcc_msg::get_urdfRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_urdf >::value();
  }
  static const char* value(const ::tcc_msg::get_urdfRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_urdfRequest> should match
// service_traits::DataType< ::tcc_msg::get_urdf >
template<>
struct DataType< ::tcc_msg::get_urdfRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_urdf >::value();
  }
  static const char* value(const ::tcc_msg::get_urdfRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::get_urdfResponse> should match
// service_traits::MD5Sum< ::tcc_msg::get_urdf >
template<>
struct MD5Sum< ::tcc_msg::get_urdfResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::get_urdf >::value();
  }
  static const char* value(const ::tcc_msg::get_urdfResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::get_urdfResponse> should match
// service_traits::DataType< ::tcc_msg::get_urdf >
template<>
struct DataType< ::tcc_msg::get_urdfResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::get_urdf >::value();
  }
  static const char* value(const ::tcc_msg::get_urdfResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_GET_URDF_H
