// Generated by gencpp from file tcc_msg/lidar_get_info.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_LIDAR_GET_INFO_H
#define TCC_MSG_MESSAGE_LIDAR_GET_INFO_H

#include <ros/service_traits.h>


#include <tcc_msg/lidar_get_infoRequest.h>
#include <tcc_msg/lidar_get_infoResponse.h>


namespace tcc_msg
{

struct lidar_get_info
{

typedef lidar_get_infoRequest Request;
typedef lidar_get_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lidar_get_info
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::lidar_get_info > {
  static const char* value()
  {
    return "d69a9b3d17121f1bdd796764ea53059a";
  }

  static const char* value(const ::tcc_msg::lidar_get_info&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::lidar_get_info > {
  static const char* value()
  {
    return "tcc_msg/lidar_get_info";
  }

  static const char* value(const ::tcc_msg::lidar_get_info&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::lidar_get_infoRequest> should match
// service_traits::MD5Sum< ::tcc_msg::lidar_get_info >
template<>
struct MD5Sum< ::tcc_msg::lidar_get_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::lidar_get_info >::value();
  }
  static const char* value(const ::tcc_msg::lidar_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::lidar_get_infoRequest> should match
// service_traits::DataType< ::tcc_msg::lidar_get_info >
template<>
struct DataType< ::tcc_msg::lidar_get_infoRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::lidar_get_info >::value();
  }
  static const char* value(const ::tcc_msg::lidar_get_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::lidar_get_infoResponse> should match
// service_traits::MD5Sum< ::tcc_msg::lidar_get_info >
template<>
struct MD5Sum< ::tcc_msg::lidar_get_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::lidar_get_info >::value();
  }
  static const char* value(const ::tcc_msg::lidar_get_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::lidar_get_infoResponse> should match
// service_traits::DataType< ::tcc_msg::lidar_get_info >
template<>
struct DataType< ::tcc_msg::lidar_get_infoResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::lidar_get_info >::value();
  }
  static const char* value(const ::tcc_msg::lidar_get_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_LIDAR_GET_INFO_H
