// Generated by gencpp from file tcc_msg/node_disable_pose_tracking.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_NODE_DISABLE_POSE_TRACKING_H
#define TCC_MSG_MESSAGE_NODE_DISABLE_POSE_TRACKING_H

#include <ros/service_traits.h>


#include <tcc_msg/node_disable_pose_trackingRequest.h>
#include <tcc_msg/node_disable_pose_trackingResponse.h>


namespace tcc_msg
{

struct node_disable_pose_tracking
{

typedef node_disable_pose_trackingRequest Request;
typedef node_disable_pose_trackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_disable_pose_tracking
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::node_disable_pose_tracking > {
  static const char* value()
  {
    return "f4bf0dd6ac618f06de5c519a76586978";
  }

  static const char* value(const ::tcc_msg::node_disable_pose_tracking&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::node_disable_pose_tracking > {
  static const char* value()
  {
    return "tcc_msg/node_disable_pose_tracking";
  }

  static const char* value(const ::tcc_msg::node_disable_pose_tracking&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::node_disable_pose_trackingRequest> should match
// service_traits::MD5Sum< ::tcc_msg::node_disable_pose_tracking >
template<>
struct MD5Sum< ::tcc_msg::node_disable_pose_trackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::node_disable_pose_tracking >::value();
  }
  static const char* value(const ::tcc_msg::node_disable_pose_trackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::node_disable_pose_trackingRequest> should match
// service_traits::DataType< ::tcc_msg::node_disable_pose_tracking >
template<>
struct DataType< ::tcc_msg::node_disable_pose_trackingRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::node_disable_pose_tracking >::value();
  }
  static const char* value(const ::tcc_msg::node_disable_pose_trackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::node_disable_pose_trackingResponse> should match
// service_traits::MD5Sum< ::tcc_msg::node_disable_pose_tracking >
template<>
struct MD5Sum< ::tcc_msg::node_disable_pose_trackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::node_disable_pose_tracking >::value();
  }
  static const char* value(const ::tcc_msg::node_disable_pose_trackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::node_disable_pose_trackingResponse> should match
// service_traits::DataType< ::tcc_msg::node_disable_pose_tracking >
template<>
struct DataType< ::tcc_msg::node_disable_pose_trackingResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::node_disable_pose_tracking >::value();
  }
  static const char* value(const ::tcc_msg::node_disable_pose_trackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_NODE_DISABLE_POSE_TRACKING_H
