// Generated by gencpp from file tcc_msg/node_get_number_of_fields.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_NODE_GET_NUMBER_OF_FIELDS_H
#define TCC_MSG_MESSAGE_NODE_GET_NUMBER_OF_FIELDS_H

#include <ros/service_traits.h>


#include <tcc_msg/node_get_number_of_fieldsRequest.h>
#include <tcc_msg/node_get_number_of_fieldsResponse.h>


namespace tcc_msg
{

struct node_get_number_of_fields
{

typedef node_get_number_of_fieldsRequest Request;
typedef node_get_number_of_fieldsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_number_of_fields
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::node_get_number_of_fields > {
  static const char* value()
  {
    return "921bd6384f46ac8733931a50b9739877";
  }

  static const char* value(const ::tcc_msg::node_get_number_of_fields&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::node_get_number_of_fields > {
  static const char* value()
  {
    return "tcc_msg/node_get_number_of_fields";
  }

  static const char* value(const ::tcc_msg::node_get_number_of_fields&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::node_get_number_of_fieldsRequest> should match
// service_traits::MD5Sum< ::tcc_msg::node_get_number_of_fields >
template<>
struct MD5Sum< ::tcc_msg::node_get_number_of_fieldsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::node_get_number_of_fields >::value();
  }
  static const char* value(const ::tcc_msg::node_get_number_of_fieldsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::node_get_number_of_fieldsRequest> should match
// service_traits::DataType< ::tcc_msg::node_get_number_of_fields >
template<>
struct DataType< ::tcc_msg::node_get_number_of_fieldsRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::node_get_number_of_fields >::value();
  }
  static const char* value(const ::tcc_msg::node_get_number_of_fieldsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::node_get_number_of_fieldsResponse> should match
// service_traits::MD5Sum< ::tcc_msg::node_get_number_of_fields >
template<>
struct MD5Sum< ::tcc_msg::node_get_number_of_fieldsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::node_get_number_of_fields >::value();
  }
  static const char* value(const ::tcc_msg::node_get_number_of_fieldsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::node_get_number_of_fieldsResponse> should match
// service_traits::DataType< ::tcc_msg::node_get_number_of_fields >
template<>
struct DataType< ::tcc_msg::node_get_number_of_fieldsResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::node_get_number_of_fields >::value();
  }
  static const char* value(const ::tcc_msg::node_get_number_of_fieldsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_NODE_GET_NUMBER_OF_FIELDS_H
