// Generated by gencpp from file tcc_msg/robot_wait_for_user_input_event.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_ROBOT_WAIT_FOR_USER_INPUT_EVENT_H
#define TCC_MSG_MESSAGE_ROBOT_WAIT_FOR_USER_INPUT_EVENT_H

#include <ros/service_traits.h>


#include <tcc_msg/robot_wait_for_user_input_eventRequest.h>
#include <tcc_msg/robot_wait_for_user_input_eventResponse.h>


namespace tcc_msg
{

struct robot_wait_for_user_input_event
{

typedef robot_wait_for_user_input_eventRequest Request;
typedef robot_wait_for_user_input_eventResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_wait_for_user_input_event
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::robot_wait_for_user_input_event > {
  static const char* value()
  {
    return "117ed5fb1f5c37c2a398a290a90fc55d";
  }

  static const char* value(const ::tcc_msg::robot_wait_for_user_input_event&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::robot_wait_for_user_input_event > {
  static const char* value()
  {
    return "tcc_msg/robot_wait_for_user_input_event";
  }

  static const char* value(const ::tcc_msg::robot_wait_for_user_input_event&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::robot_wait_for_user_input_eventRequest> should match
// service_traits::MD5Sum< ::tcc_msg::robot_wait_for_user_input_event >
template<>
struct MD5Sum< ::tcc_msg::robot_wait_for_user_input_eventRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::robot_wait_for_user_input_event >::value();
  }
  static const char* value(const ::tcc_msg::robot_wait_for_user_input_eventRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::robot_wait_for_user_input_eventRequest> should match
// service_traits::DataType< ::tcc_msg::robot_wait_for_user_input_event >
template<>
struct DataType< ::tcc_msg::robot_wait_for_user_input_eventRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::robot_wait_for_user_input_event >::value();
  }
  static const char* value(const ::tcc_msg::robot_wait_for_user_input_eventRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::robot_wait_for_user_input_eventResponse> should match
// service_traits::MD5Sum< ::tcc_msg::robot_wait_for_user_input_event >
template<>
struct MD5Sum< ::tcc_msg::robot_wait_for_user_input_eventResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::robot_wait_for_user_input_event >::value();
  }
  static const char* value(const ::tcc_msg::robot_wait_for_user_input_eventResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::robot_wait_for_user_input_eventResponse> should match
// service_traits::DataType< ::tcc_msg::robot_wait_for_user_input_event >
template<>
struct DataType< ::tcc_msg::robot_wait_for_user_input_eventResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::robot_wait_for_user_input_event >::value();
  }
  static const char* value(const ::tcc_msg::robot_wait_for_user_input_eventResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_ROBOT_WAIT_FOR_USER_INPUT_EVENT_H
