// Generated by gencpp from file tcc_msg/speaker_speak.msg
// DO NOT EDIT!


#ifndef TCC_MSG_MESSAGE_SPEAKER_SPEAK_H
#define TCC_MSG_MESSAGE_SPEAKER_SPEAK_H

#include <ros/service_traits.h>


#include <tcc_msg/speaker_speakRequest.h>
#include <tcc_msg/speaker_speakResponse.h>


namespace tcc_msg
{

struct speaker_speak
{

typedef speaker_speakRequest Request;
typedef speaker_speakResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speaker_speak
} // namespace tcc_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tcc_msg::speaker_speak > {
  static const char* value()
  {
    return "bc987d1a1839d594218b7c1d6a77ba5e";
  }

  static const char* value(const ::tcc_msg::speaker_speak&) { return value(); }
};

template<>
struct DataType< ::tcc_msg::speaker_speak > {
  static const char* value()
  {
    return "tcc_msg/speaker_speak";
  }

  static const char* value(const ::tcc_msg::speaker_speak&) { return value(); }
};


// service_traits::MD5Sum< ::tcc_msg::speaker_speakRequest> should match
// service_traits::MD5Sum< ::tcc_msg::speaker_speak >
template<>
struct MD5Sum< ::tcc_msg::speaker_speakRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::speaker_speak >::value();
  }
  static const char* value(const ::tcc_msg::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::speaker_speakRequest> should match
// service_traits::DataType< ::tcc_msg::speaker_speak >
template<>
struct DataType< ::tcc_msg::speaker_speakRequest>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::speaker_speak >::value();
  }
  static const char* value(const ::tcc_msg::speaker_speakRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tcc_msg::speaker_speakResponse> should match
// service_traits::MD5Sum< ::tcc_msg::speaker_speak >
template<>
struct MD5Sum< ::tcc_msg::speaker_speakResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tcc_msg::speaker_speak >::value();
  }
  static const char* value(const ::tcc_msg::speaker_speakResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tcc_msg::speaker_speakResponse> should match
// service_traits::DataType< ::tcc_msg::speaker_speak >
template<>
struct DataType< ::tcc_msg::speaker_speakResponse>
{
  static const char* value()
  {
    return DataType< ::tcc_msg::speaker_speak >::value();
  }
  static const char* value(const ::tcc_msg::speaker_speakResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TCC_MSG_MESSAGE_SPEAKER_SPEAK_H
