// Generated by gencpp from file comm_webots/display_image_new.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_DISPLAY_IMAGE_NEW_H
#define COMM_WEBOTS_MESSAGE_DISPLAY_IMAGE_NEW_H

#include <ros/service_traits.h>


#include <comm_webots/display_image_newRequest.h>
#include <comm_webots/display_image_newResponse.h>


namespace comm_webots
{

struct display_image_new
{

typedef display_image_newRequest Request;
typedef display_image_newResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_image_new
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::display_image_new > {
  static const char* value()
  {
    return "80a036f354960d09033ab0f8d6dffcf7";
  }

  static const char* value(const ::comm_webots::display_image_new&) { return value(); }
};

template<>
struct DataType< ::comm_webots::display_image_new > {
  static const char* value()
  {
    return "comm_webots/display_image_new";
  }

  static const char* value(const ::comm_webots::display_image_new&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::display_image_newRequest> should match
// service_traits::MD5Sum< ::comm_webots::display_image_new >
template<>
struct MD5Sum< ::comm_webots::display_image_newRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_image_new >::value();
  }
  static const char* value(const ::comm_webots::display_image_newRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_image_newRequest> should match
// service_traits::DataType< ::comm_webots::display_image_new >
template<>
struct DataType< ::comm_webots::display_image_newRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_image_new >::value();
  }
  static const char* value(const ::comm_webots::display_image_newRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::display_image_newResponse> should match
// service_traits::MD5Sum< ::comm_webots::display_image_new >
template<>
struct MD5Sum< ::comm_webots::display_image_newResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_image_new >::value();
  }
  static const char* value(const ::comm_webots::display_image_newResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_image_newResponse> should match
// service_traits::DataType< ::comm_webots::display_image_new >
template<>
struct DataType< ::comm_webots::display_image_newResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_image_new >::value();
  }
  static const char* value(const ::comm_webots::display_image_newResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_DISPLAY_IMAGE_NEW_H
