// Generated by gencpp from file comm_webots/display_draw_rectangle.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_RECTANGLE_H
#define COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_RECTANGLE_H

#include <ros/service_traits.h>


#include <comm_webots/display_draw_rectangleRequest.h>
#include <comm_webots/display_draw_rectangleResponse.h>


namespace comm_webots
{

struct display_draw_rectangle
{

typedef display_draw_rectangleRequest Request;
typedef display_draw_rectangleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_rectangle
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::display_draw_rectangle > {
  static const char* value()
  {
    return "f7d77dd6f16a5d7e8ba643de53791446";
  }

  static const char* value(const ::comm_webots::display_draw_rectangle&) { return value(); }
};

template<>
struct DataType< ::comm_webots::display_draw_rectangle > {
  static const char* value()
  {
    return "comm_webots/display_draw_rectangle";
  }

  static const char* value(const ::comm_webots::display_draw_rectangle&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::display_draw_rectangleRequest> should match
// service_traits::MD5Sum< ::comm_webots::display_draw_rectangle >
template<>
struct MD5Sum< ::comm_webots::display_draw_rectangleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_draw_rectangle >::value();
  }
  static const char* value(const ::comm_webots::display_draw_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_draw_rectangleRequest> should match
// service_traits::DataType< ::comm_webots::display_draw_rectangle >
template<>
struct DataType< ::comm_webots::display_draw_rectangleRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_draw_rectangle >::value();
  }
  static const char* value(const ::comm_webots::display_draw_rectangleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::display_draw_rectangleResponse> should match
// service_traits::MD5Sum< ::comm_webots::display_draw_rectangle >
template<>
struct MD5Sum< ::comm_webots::display_draw_rectangleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_draw_rectangle >::value();
  }
  static const char* value(const ::comm_webots::display_draw_rectangleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_draw_rectangleResponse> should match
// service_traits::DataType< ::comm_webots::display_draw_rectangle >
template<>
struct DataType< ::comm_webots::display_draw_rectangleResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_draw_rectangle >::value();
  }
  static const char* value(const ::comm_webots::display_draw_rectangleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_RECTANGLE_H
