// Generated by gencpp from file comm_webots/display_draw_oval.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_OVAL_H
#define COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_OVAL_H

#include <ros/service_traits.h>


#include <comm_webots/display_draw_ovalRequest.h>
#include <comm_webots/display_draw_ovalResponse.h>


namespace comm_webots
{

struct display_draw_oval
{

typedef display_draw_ovalRequest Request;
typedef display_draw_ovalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct display_draw_oval
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::display_draw_oval > {
  static const char* value()
  {
    return "257804d9f2e4639bae589e190802d29f";
  }

  static const char* value(const ::comm_webots::display_draw_oval&) { return value(); }
};

template<>
struct DataType< ::comm_webots::display_draw_oval > {
  static const char* value()
  {
    return "comm_webots/display_draw_oval";
  }

  static const char* value(const ::comm_webots::display_draw_oval&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::display_draw_ovalRequest> should match
// service_traits::MD5Sum< ::comm_webots::display_draw_oval >
template<>
struct MD5Sum< ::comm_webots::display_draw_ovalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_draw_oval >::value();
  }
  static const char* value(const ::comm_webots::display_draw_ovalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_draw_ovalRequest> should match
// service_traits::DataType< ::comm_webots::display_draw_oval >
template<>
struct DataType< ::comm_webots::display_draw_ovalRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_draw_oval >::value();
  }
  static const char* value(const ::comm_webots::display_draw_ovalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::display_draw_ovalResponse> should match
// service_traits::MD5Sum< ::comm_webots::display_draw_oval >
template<>
struct MD5Sum< ::comm_webots::display_draw_ovalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::display_draw_oval >::value();
  }
  static const char* value(const ::comm_webots::display_draw_ovalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::display_draw_ovalResponse> should match
// service_traits::DataType< ::comm_webots::display_draw_oval >
template<>
struct DataType< ::comm_webots::display_draw_ovalResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::display_draw_oval >::value();
  }
  static const char* value(const ::comm_webots::display_draw_ovalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_DISPLAY_DRAW_OVAL_H
