// Generated by gencpp from file comm_webots/field_get_name.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_FIELD_GET_NAME_H
#define COMM_WEBOTS_MESSAGE_FIELD_GET_NAME_H

#include <ros/service_traits.h>


#include <comm_webots/field_get_nameRequest.h>
#include <comm_webots/field_get_nameResponse.h>


namespace comm_webots
{

struct field_get_name
{

typedef field_get_nameRequest Request;
typedef field_get_nameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_name
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::field_get_name > {
  static const char* value()
  {
    return "5a98464d3ca05386300217ec41ec161f";
  }

  static const char* value(const ::comm_webots::field_get_name&) { return value(); }
};

template<>
struct DataType< ::comm_webots::field_get_name > {
  static const char* value()
  {
    return "comm_webots/field_get_name";
  }

  static const char* value(const ::comm_webots::field_get_name&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::field_get_nameRequest> should match
// service_traits::MD5Sum< ::comm_webots::field_get_name >
template<>
struct MD5Sum< ::comm_webots::field_get_nameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::field_get_name >::value();
  }
  static const char* value(const ::comm_webots::field_get_nameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::field_get_nameRequest> should match
// service_traits::DataType< ::comm_webots::field_get_name >
template<>
struct DataType< ::comm_webots::field_get_nameRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::field_get_name >::value();
  }
  static const char* value(const ::comm_webots::field_get_nameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::field_get_nameResponse> should match
// service_traits::MD5Sum< ::comm_webots::field_get_name >
template<>
struct MD5Sum< ::comm_webots::field_get_nameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::field_get_name >::value();
  }
  static const char* value(const ::comm_webots::field_get_nameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::field_get_nameResponse> should match
// service_traits::DataType< ::comm_webots::field_get_name >
template<>
struct DataType< ::comm_webots::field_get_nameResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::field_get_name >::value();
  }
  static const char* value(const ::comm_webots::field_get_nameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_FIELD_GET_NAME_H
