// Generated by gencpp from file comm_webots/field_get_vec2f.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_FIELD_GET_VEC2F_H
#define COMM_WEBOTS_MESSAGE_FIELD_GET_VEC2F_H

#include <ros/service_traits.h>


#include <comm_webots/field_get_vec2fRequest.h>
#include <comm_webots/field_get_vec2fResponse.h>


namespace comm_webots
{

struct field_get_vec2f
{

typedef field_get_vec2fRequest Request;
typedef field_get_vec2fResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct field_get_vec2f
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::field_get_vec2f > {
  static const char* value()
  {
    return "5ba75d9d095ca14bcb57c58ac3b63422";
  }

  static const char* value(const ::comm_webots::field_get_vec2f&) { return value(); }
};

template<>
struct DataType< ::comm_webots::field_get_vec2f > {
  static const char* value()
  {
    return "comm_webots/field_get_vec2f";
  }

  static const char* value(const ::comm_webots::field_get_vec2f&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::field_get_vec2fRequest> should match
// service_traits::MD5Sum< ::comm_webots::field_get_vec2f >
template<>
struct MD5Sum< ::comm_webots::field_get_vec2fRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::field_get_vec2f >::value();
  }
  static const char* value(const ::comm_webots::field_get_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::field_get_vec2fRequest> should match
// service_traits::DataType< ::comm_webots::field_get_vec2f >
template<>
struct DataType< ::comm_webots::field_get_vec2fRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::field_get_vec2f >::value();
  }
  static const char* value(const ::comm_webots::field_get_vec2fRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::field_get_vec2fResponse> should match
// service_traits::MD5Sum< ::comm_webots::field_get_vec2f >
template<>
struct MD5Sum< ::comm_webots::field_get_vec2fResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::field_get_vec2f >::value();
  }
  static const char* value(const ::comm_webots::field_get_vec2fResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::field_get_vec2fResponse> should match
// service_traits::DataType< ::comm_webots::field_get_vec2f >
template<>
struct DataType< ::comm_webots::field_get_vec2fResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::field_get_vec2f >::value();
  }
  static const char* value(const ::comm_webots::field_get_vec2fResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_FIELD_GET_VEC2F_H
