// Generated by gencpp from file comm_webots/get_uint64.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_GET_UINT64_H
#define COMM_WEBOTS_MESSAGE_GET_UINT64_H

#include <ros/service_traits.h>


#include <comm_webots/get_uint64Request.h>
#include <comm_webots/get_uint64Response.h>


namespace comm_webots
{

struct get_uint64
{

typedef get_uint64Request Request;
typedef get_uint64Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_uint64
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::get_uint64 > {
  static const char* value()
  {
    return "d531f9d37648dc4de8bf2e757ee280a0";
  }

  static const char* value(const ::comm_webots::get_uint64&) { return value(); }
};

template<>
struct DataType< ::comm_webots::get_uint64 > {
  static const char* value()
  {
    return "comm_webots/get_uint64";
  }

  static const char* value(const ::comm_webots::get_uint64&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::get_uint64Request> should match
// service_traits::MD5Sum< ::comm_webots::get_uint64 >
template<>
struct MD5Sum< ::comm_webots::get_uint64Request>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::get_uint64 >::value();
  }
  static const char* value(const ::comm_webots::get_uint64Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::get_uint64Request> should match
// service_traits::DataType< ::comm_webots::get_uint64 >
template<>
struct DataType< ::comm_webots::get_uint64Request>
{
  static const char* value()
  {
    return DataType< ::comm_webots::get_uint64 >::value();
  }
  static const char* value(const ::comm_webots::get_uint64Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::get_uint64Response> should match
// service_traits::MD5Sum< ::comm_webots::get_uint64 >
template<>
struct MD5Sum< ::comm_webots::get_uint64Response>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::get_uint64 >::value();
  }
  static const char* value(const ::comm_webots::get_uint64Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::get_uint64Response> should match
// service_traits::DataType< ::comm_webots::get_uint64 >
template<>
struct DataType< ::comm_webots::get_uint64Response>
{
  static const char* value()
  {
    return DataType< ::comm_webots::get_uint64 >::value();
  }
  static const char* value(const ::comm_webots::get_uint64Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_GET_UINT64_H
