// Generated by gencpp from file comm_webots/get_int.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_GET_INT_H
#define COMM_WEBOTS_MESSAGE_GET_INT_H

#include <ros/service_traits.h>


#include <comm_webots/get_intRequest.h>
#include <comm_webots/get_intResponse.h>


namespace comm_webots
{

struct get_int
{

typedef get_intRequest Request;
typedef get_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_int
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::get_int > {
  static const char* value()
  {
    return "73dfae6ec9145dcc45d5ed973079e912";
  }

  static const char* value(const ::comm_webots::get_int&) { return value(); }
};

template<>
struct DataType< ::comm_webots::get_int > {
  static const char* value()
  {
    return "comm_webots/get_int";
  }

  static const char* value(const ::comm_webots::get_int&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::get_intRequest> should match
// service_traits::MD5Sum< ::comm_webots::get_int >
template<>
struct MD5Sum< ::comm_webots::get_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::get_int >::value();
  }
  static const char* value(const ::comm_webots::get_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::get_intRequest> should match
// service_traits::DataType< ::comm_webots::get_int >
template<>
struct DataType< ::comm_webots::get_intRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::get_int >::value();
  }
  static const char* value(const ::comm_webots::get_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::get_intResponse> should match
// service_traits::MD5Sum< ::comm_webots::get_int >
template<>
struct MD5Sum< ::comm_webots::get_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::get_int >::value();
  }
  static const char* value(const ::comm_webots::get_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::get_intResponse> should match
// service_traits::DataType< ::comm_webots::get_int >
template<>
struct DataType< ::comm_webots::get_intResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::get_int >::value();
  }
  static const char* value(const ::comm_webots::get_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_GET_INT_H
