// Generated by gencpp from file comm_webots/lidar_get_layer_range_image.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_LIDAR_GET_LAYER_RANGE_IMAGE_H
#define COMM_WEBOTS_MESSAGE_LIDAR_GET_LAYER_RANGE_IMAGE_H

#include <ros/service_traits.h>


#include <comm_webots/lidar_get_layer_range_imageRequest.h>
#include <comm_webots/lidar_get_layer_range_imageResponse.h>


namespace comm_webots
{

struct lidar_get_layer_range_image
{

typedef lidar_get_layer_range_imageRequest Request;
typedef lidar_get_layer_range_imageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lidar_get_layer_range_image
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::lidar_get_layer_range_image > {
  static const char* value()
  {
    return "4d25c95147eb8b7728942d09e84dc175";
  }

  static const char* value(const ::comm_webots::lidar_get_layer_range_image&) { return value(); }
};

template<>
struct DataType< ::comm_webots::lidar_get_layer_range_image > {
  static const char* value()
  {
    return "comm_webots/lidar_get_layer_range_image";
  }

  static const char* value(const ::comm_webots::lidar_get_layer_range_image&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::lidar_get_layer_range_imageRequest> should match
// service_traits::MD5Sum< ::comm_webots::lidar_get_layer_range_image >
template<>
struct MD5Sum< ::comm_webots::lidar_get_layer_range_imageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::lidar_get_layer_range_image >::value();
  }
  static const char* value(const ::comm_webots::lidar_get_layer_range_imageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::lidar_get_layer_range_imageRequest> should match
// service_traits::DataType< ::comm_webots::lidar_get_layer_range_image >
template<>
struct DataType< ::comm_webots::lidar_get_layer_range_imageRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::lidar_get_layer_range_image >::value();
  }
  static const char* value(const ::comm_webots::lidar_get_layer_range_imageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::lidar_get_layer_range_imageResponse> should match
// service_traits::MD5Sum< ::comm_webots::lidar_get_layer_range_image >
template<>
struct MD5Sum< ::comm_webots::lidar_get_layer_range_imageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::lidar_get_layer_range_image >::value();
  }
  static const char* value(const ::comm_webots::lidar_get_layer_range_imageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::lidar_get_layer_range_imageResponse> should match
// service_traits::DataType< ::comm_webots::lidar_get_layer_range_image >
template<>
struct DataType< ::comm_webots::lidar_get_layer_range_imageResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::lidar_get_layer_range_image >::value();
  }
  static const char* value(const ::comm_webots::lidar_get_layer_range_imageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_LIDAR_GET_LAYER_RANGE_IMAGE_H
