// Generated by gencpp from file comm_webots/node_enable_pose_tracking.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_NODE_ENABLE_POSE_TRACKING_H
#define COMM_WEBOTS_MESSAGE_NODE_ENABLE_POSE_TRACKING_H

#include <ros/service_traits.h>


#include <comm_webots/node_enable_pose_trackingRequest.h>
#include <comm_webots/node_enable_pose_trackingResponse.h>


namespace comm_webots
{

struct node_enable_pose_tracking
{

typedef node_enable_pose_trackingRequest Request;
typedef node_enable_pose_trackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_enable_pose_tracking
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::node_enable_pose_tracking > {
  static const char* value()
  {
    return "8cd216b812da1c93f2089a1c0f3ffed3";
  }

  static const char* value(const ::comm_webots::node_enable_pose_tracking&) { return value(); }
};

template<>
struct DataType< ::comm_webots::node_enable_pose_tracking > {
  static const char* value()
  {
    return "comm_webots/node_enable_pose_tracking";
  }

  static const char* value(const ::comm_webots::node_enable_pose_tracking&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::node_enable_pose_trackingRequest> should match
// service_traits::MD5Sum< ::comm_webots::node_enable_pose_tracking >
template<>
struct MD5Sum< ::comm_webots::node_enable_pose_trackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::node_enable_pose_tracking >::value();
  }
  static const char* value(const ::comm_webots::node_enable_pose_trackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::node_enable_pose_trackingRequest> should match
// service_traits::DataType< ::comm_webots::node_enable_pose_tracking >
template<>
struct DataType< ::comm_webots::node_enable_pose_trackingRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::node_enable_pose_tracking >::value();
  }
  static const char* value(const ::comm_webots::node_enable_pose_trackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::node_enable_pose_trackingResponse> should match
// service_traits::MD5Sum< ::comm_webots::node_enable_pose_tracking >
template<>
struct MD5Sum< ::comm_webots::node_enable_pose_trackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::node_enable_pose_tracking >::value();
  }
  static const char* value(const ::comm_webots::node_enable_pose_trackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::node_enable_pose_trackingResponse> should match
// service_traits::DataType< ::comm_webots::node_enable_pose_tracking >
template<>
struct DataType< ::comm_webots::node_enable_pose_trackingResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::node_enable_pose_tracking >::value();
  }
  static const char* value(const ::comm_webots::node_enable_pose_trackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_NODE_ENABLE_POSE_TRACKING_H
