// Generated by gencpp from file comm_webots/pen_set_ink_colorRequest.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_PEN_SET_INK_COLORREQUEST_H
#define COMM_WEBOTS_MESSAGE_PEN_SET_INK_COLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_webots
{
template <class ContainerAllocator>
struct pen_set_ink_colorRequest_
{
  typedef pen_set_ink_colorRequest_<ContainerAllocator> Type;

  pen_set_ink_colorRequest_()
    : color(0)
    , density(0.0)  {
    }
  pen_set_ink_colorRequest_(const ContainerAllocator& _alloc)
    : color(0)
    , density(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _color_type;
  _color_type color;

   typedef double _density_type;
  _density_type density;





  typedef boost::shared_ptr< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pen_set_ink_colorRequest_

typedef ::comm_webots::pen_set_ink_colorRequest_<std::allocator<void> > pen_set_ink_colorRequest;

typedef boost::shared_ptr< ::comm_webots::pen_set_ink_colorRequest > pen_set_ink_colorRequestPtr;
typedef boost::shared_ptr< ::comm_webots::pen_set_ink_colorRequest const> pen_set_ink_colorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator1> & lhs, const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color == rhs.color &&
    lhs.density == rhs.density;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator1> & lhs, const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_webots

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "156d8b74482921c561726aaf09907de8";
  }

  static const char* value(const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x156d8b74482921c5ULL;
  static const uint64_t static_value2 = 0x61726aaf09907de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_webots/pen_set_ink_colorRequest";
  }

  static const char* value(const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 color\n"
"float64 density\n"
;
  }

  static const char* value(const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color);
      stream.next(m.density);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pen_set_ink_colorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_webots::pen_set_ink_colorRequest_<ContainerAllocator>& v)
  {
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
    s << indent << "density: ";
    Printer<double>::stream(s, indent + "  ", v.density);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_PEN_SET_INK_COLORREQUEST_H
