// Generated by gencpp from file comm_webots/set_floatRequest.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_SET_FLOATREQUEST_H
#define COMM_WEBOTS_MESSAGE_SET_FLOATREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_webots
{
template <class ContainerAllocator>
struct set_floatRequest_
{
  typedef set_floatRequest_<ContainerAllocator> Type;

  set_floatRequest_()
    : value(0.0)  {
    }
  set_floatRequest_(const ContainerAllocator& _alloc)
    : value(0.0)  {
  (void)_alloc;
    }



   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::comm_webots::set_floatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_webots::set_floatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_floatRequest_

typedef ::comm_webots::set_floatRequest_<std::allocator<void> > set_floatRequest;

typedef boost::shared_ptr< ::comm_webots::set_floatRequest > set_floatRequestPtr;
typedef boost::shared_ptr< ::comm_webots::set_floatRequest const> set_floatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_webots::set_floatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_webots::set_floatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::comm_webots::set_floatRequest_<ContainerAllocator1> & lhs, const ::comm_webots::set_floatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::comm_webots::set_floatRequest_<ContainerAllocator1> & lhs, const ::comm_webots::set_floatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace comm_webots

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::comm_webots::set_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_webots::set_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_webots::set_floatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_webots::set_floatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_webots::set_floatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_webots::set_floatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_webots::set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b1594d2b74931ef8fe7be8e2d594455";
  }

  static const char* value(const ::comm_webots::set_floatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b1594d2b74931efULL;
  static const uint64_t static_value2 = 0x8fe7be8e2d594455ULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_webots::set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_webots/set_floatRequest";
  }

  static const char* value(const ::comm_webots::set_floatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_webots::set_floatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 value\n"
;
  }

  static const char* value(const ::comm_webots::set_floatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_webots::set_floatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_floatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_webots::set_floatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_webots::set_floatRequest_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_SET_FLOATREQUEST_H
