// Generated by gencpp from file comm_webots/set_bool.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_SET_BOOL_H
#define COMM_WEBOTS_MESSAGE_SET_BOOL_H

#include <ros/service_traits.h>


#include <comm_webots/set_boolRequest.h>
#include <comm_webots/set_boolResponse.h>


namespace comm_webots
{

struct set_bool
{

typedef set_boolRequest Request;
typedef set_boolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_bool
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::set_bool > {
  static const char* value()
  {
    return "24a0f9fd764459b7e35d04a0dd83dd11";
  }

  static const char* value(const ::comm_webots::set_bool&) { return value(); }
};

template<>
struct DataType< ::comm_webots::set_bool > {
  static const char* value()
  {
    return "comm_webots/set_bool";
  }

  static const char* value(const ::comm_webots::set_bool&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::set_boolRequest> should match
// service_traits::MD5Sum< ::comm_webots::set_bool >
template<>
struct MD5Sum< ::comm_webots::set_boolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_bool >::value();
  }
  static const char* value(const ::comm_webots::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_boolRequest> should match
// service_traits::DataType< ::comm_webots::set_bool >
template<>
struct DataType< ::comm_webots::set_boolRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_bool >::value();
  }
  static const char* value(const ::comm_webots::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::set_boolResponse> should match
// service_traits::MD5Sum< ::comm_webots::set_bool >
template<>
struct MD5Sum< ::comm_webots::set_boolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_bool >::value();
  }
  static const char* value(const ::comm_webots::set_boolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_boolResponse> should match
// service_traits::DataType< ::comm_webots::set_bool >
template<>
struct DataType< ::comm_webots::set_boolResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_bool >::value();
  }
  static const char* value(const ::comm_webots::set_boolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_SET_BOOL_H
