// Generated by gencpp from file comm_webots/set_float_array.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_SET_FLOAT_ARRAY_H
#define COMM_WEBOTS_MESSAGE_SET_FLOAT_ARRAY_H

#include <ros/service_traits.h>


#include <comm_webots/set_float_arrayRequest.h>
#include <comm_webots/set_float_arrayResponse.h>


namespace comm_webots
{

struct set_float_array
{

typedef set_float_arrayRequest Request;
typedef set_float_arrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_float_array
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::set_float_array > {
  static const char* value()
  {
    return "0fcc5d2c24929b6dbbf415b9579ddce4";
  }

  static const char* value(const ::comm_webots::set_float_array&) { return value(); }
};

template<>
struct DataType< ::comm_webots::set_float_array > {
  static const char* value()
  {
    return "comm_webots/set_float_array";
  }

  static const char* value(const ::comm_webots::set_float_array&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::set_float_arrayRequest> should match
// service_traits::MD5Sum< ::comm_webots::set_float_array >
template<>
struct MD5Sum< ::comm_webots::set_float_arrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_float_array >::value();
  }
  static const char* value(const ::comm_webots::set_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_float_arrayRequest> should match
// service_traits::DataType< ::comm_webots::set_float_array >
template<>
struct DataType< ::comm_webots::set_float_arrayRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_float_array >::value();
  }
  static const char* value(const ::comm_webots::set_float_arrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::set_float_arrayResponse> should match
// service_traits::MD5Sum< ::comm_webots::set_float_array >
template<>
struct MD5Sum< ::comm_webots::set_float_arrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_float_array >::value();
  }
  static const char* value(const ::comm_webots::set_float_arrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_float_arrayResponse> should match
// service_traits::DataType< ::comm_webots::set_float_array >
template<>
struct DataType< ::comm_webots::set_float_arrayResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_float_array >::value();
  }
  static const char* value(const ::comm_webots::set_float_arrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_SET_FLOAT_ARRAY_H
