// Generated by gencpp from file comm_webots/set_string.msg
// DO NOT EDIT!


#ifndef COMM_WEBOTS_MESSAGE_SET_STRING_H
#define COMM_WEBOTS_MESSAGE_SET_STRING_H

#include <ros/service_traits.h>


#include <comm_webots/set_stringRequest.h>
#include <comm_webots/set_stringResponse.h>


namespace comm_webots
{

struct set_string
{

typedef set_stringRequest Request;
typedef set_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_string
} // namespace comm_webots


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_webots::set_string > {
  static const char* value()
  {
    return "0462bc0e878964615c49ad8ef45df667";
  }

  static const char* value(const ::comm_webots::set_string&) { return value(); }
};

template<>
struct DataType< ::comm_webots::set_string > {
  static const char* value()
  {
    return "comm_webots/set_string";
  }

  static const char* value(const ::comm_webots::set_string&) { return value(); }
};


// service_traits::MD5Sum< ::comm_webots::set_stringRequest> should match
// service_traits::MD5Sum< ::comm_webots::set_string >
template<>
struct MD5Sum< ::comm_webots::set_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_string >::value();
  }
  static const char* value(const ::comm_webots::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_stringRequest> should match
// service_traits::DataType< ::comm_webots::set_string >
template<>
struct DataType< ::comm_webots::set_stringRequest>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_string >::value();
  }
  static const char* value(const ::comm_webots::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_webots::set_stringResponse> should match
// service_traits::MD5Sum< ::comm_webots::set_string >
template<>
struct MD5Sum< ::comm_webots::set_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_webots::set_string >::value();
  }
  static const char* value(const ::comm_webots::set_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_webots::set_stringResponse> should match
// service_traits::DataType< ::comm_webots::set_string >
template<>
struct DataType< ::comm_webots::set_stringResponse>
{
  static const char* value()
  {
    return DataType< ::comm_webots::set_string >::value();
  }
  static const char* value(const ::comm_webots::set_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_WEBOTS_MESSAGE_SET_STRING_H
